In [2]:
import pandas as pd
import pandera as pa
import numpy as np
from nptyping import NDArray, Shape, Int64

## DataFrame

   * add new column
      *  one column
      *  two or more columns

   * delete column

   * change data type of columns

   * map

   * apply
      *  on one column
      *  more than one column

   * concat
      *  axis
         *   axis = 0 (top to bottom)
         *   axis = 1 (left to right)

   * describe dataframe
     *   df.info() # total index, columns names and data type, total fill cells
     *   df.describe() # mean, std, min # statistical properties | apply only numeric columns
     *   df.head() # first 5 rows
     *   df.tail() # last 5 rows

   * dataframe.sample() # select samples

In [7]:
total : int = 10000
s1 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(80, 100, (total,5))
ss1 : pd.DataFrame = pd.DataFrame(s1,columns=['s1','s2','s3','s4','s5'])

s2 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(70, 79,(total,5))
ss2 : pd.DataFrame = pd.DataFrame(s2,columns=['s1','s2','s3','s4','s5'])

s3 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(60, 69, (total,5))
ss3 : pd.DataFrame = pd.DataFrame(s3,columns=['s1','s2','s3','s4','s5'])

s4 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(50, 59, (total,5))
ss4 : pd.DataFrame = pd.DataFrame(s4,columns=['s1','s2','s3','s4','s5'])

s5 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(40, 49, (total,5))
ss5 : pd.DataFrame = pd.DataFrame(s5,columns=['s1','s2','s3','s4','s5'])

s6 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(33, 39, (total,5))
ss6 : pd.DataFrame = pd.DataFrame(s6,columns=['s1','s2','s3','s4','s5'])

s7 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(0, 32, (total,5))
ss7 : pd.DataFrame = pd.DataFrame(s7,columns=['s1','s2','s3','s4','s5'])


print(s1)
print(s2)
print(s3)
print(s4)
print(s5)


print(len(ss1))
print(len(ss2))
print(len(ss3))
print(len(ss4))
print(len(ss5))
print(len(ss6))
print(len(ss7))

[[93 83 94 92 93]
 [86 84 90 85 94]
 [92 94 84 81 93]
 ...
 [92 89 86 92 82]
 [91 89 83 96 91]
 [86 90 84 82 88]]
[[72 78 76 74 77]
 [75 72 75 74 78]
 [70 71 72 76 77]
 ...
 [77 78 72 72 78]
 [74 78 71 70 71]
 [75 75 70 76 70]]
[[60 62 62 66 65]
 [63 61 64 60 68]
 [61 60 64 61 68]
 ...
 [63 62 66 68 63]
 [63 68 67 68 66]
 [63 66 62 60 65]]
[[55 52 57 50 51]
 [51 58 53 54 53]
 [51 53 55 54 53]
 ...
 [50 57 55 57 54]
 [50 55 55 55 57]
 [50 57 56 51 53]]
[[48 43 47 42 47]
 [41 40 43 44 47]
 [44 45 40 43 48]
 ...
 [46 40 44 45 43]
 [42 47 45 47 42]
 [41 41 45 43 48]]
10000
10000
10000
10000
10000
10000
10000


In [11]:
ss5

s1  s2  s3  s4  s5
0     48  43  47  42  47
1     41  40  43  44  47
2     44  45  40  43  48
3     47  45  48  46  42
4     42  44  46  44  42
...   ..  ..  ..  ..  ..
9995  40  45  47  44  40
9996  45  45  45  44  42
9997  46  40  44  45  43
9998  42  47  45  47  42
9999  41  41  45  43  48

[10000 rows x 5 columns]

In [15]:
df : pd.DataFrame = pd.concat([ss1,ss2,ss3,ss4,ss5,ss6,ss7]).reset_index(drop=True)

display(df.info())
print("================================================================")
display(df.describe())
print("================================================================")
display(df.head())# .head(n=60)
display("================================================================")
display(df.tail())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   s1      70000 non-null  int32
 1   s2      70000 non-null  int32
 2   s3      70000 non-null  int32
 3   s4      70000 non-null  int32
 4   s5      70000 non-null  int32
dtypes: int32(5)
memory usage: 1.3 MB


None

s1            s2            s3            s4            s5
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000
mean      53.813343     53.781900     53.797557     53.783843     53.799457
std       23.395880     23.370368     23.395391     23.360619     23.362845
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%       37.000000     37.000000     37.000000     37.000000     37.000000
50%       54.000000     54.000000     54.000000     54.000000     54.000000
75%       72.000000     72.000000     72.000000     72.000000     72.000000
max       99.000000     99.000000     99.000000     99.000000     99.000000

s1  s2  s3  s4  s5
0  93  83  94  92  93
1  86  84  90  85  94
2  92  94  84  81  93
3  90  88  93  95  82
4  84  86  92  85  90

'================================================================'

s1  s2  s3  s4  s5
69995  31  27  24  29  26
69996  22  30  19  22  23
69997  26  26  26  18   9
69998  28  22   8  28  30
69999   8  12  28   9   6

In [16]:
df.to_csv("student.csv", index=False)

In [17]:
df1 : pd.DataFrame = pd.read_csv("./student.csv")
df1.head()

s1  s2  s3  s4  s5
0  93  83  94  92  93
1  86  84  90  85  94
2  92  94  84  81  93
3  90  88  93  95  82
4  84  86  92  85  90

## Apply operations on columns

   * Extract one column from DataFrame
      *  dataframe['column']
          *  add new column
          *  get column with space between columns text
      *  dataframe.column
          *  not add new column
          *  not get column with space between columns text
   * Extract two or more columns from DataFrame
      *  dataframe[['column1', 'column2']]
          *  pass list into DataFrame



In [18]:
df.head()

s1  s2  s3  s4  s5
0  93  83  94  92  93
1  86  84  90  85  94
2  92  94  84  81  93
3  90  88  93  95  82
4  84  86  92  85  90

In [19]:
df['s5']
# df['s5 physic']

0        93
1        94
2        93
3        82
4        90
         ..
69995    26
69996    23
69997     9
69998    30
69999     6
Name: s5, Length: 70000, dtype: int32

In [20]:
df.s5

0        93
1        94
2        93
3        82
4        90
         ..
69995    26
69996    23
69997     9
69998    30
69999     6
Name: s5, Length: 70000, dtype: int32

In [21]:
df[["s1","s5","s3","s1"]]

s1  s5  s3  s1
0      93  93  94  93
1      86  94  90  86
2      92  93  84  92
3      90  82  93  90
4      84  90  92  84
...    ..  ..  ..  ..
69995  31  26  24  31
69996  22  23  19  22
69997  26   9  26  26
69998  28  30   8  28
69999   8   6  28   8

[70000 rows x 4 columns]

## Add new column

 *   Addition operation on column



In [22]:
df.head()

s1  s2  s3  s4  s5
0  93  83  94  92  93
1  86  84  90  85  94
2  92  94  84  81  93
3  90  88  93  95  82
4  84  86  92  85  90

In [28]:
df['Total'] = 500 # add new column
# df['Total'] = 300 # update column values
# df['Total'] = 500 # add new column
del df['Total']

df



s1  s2  s3  s4  s5
0      93  83  94  92  93
1      86  84  90  85  94
2      92  94  84  81  93
3      90  88  93  95  82
4      84  86  92  85  90
...    ..  ..  ..  ..  ..
69995  31  27  24  29  26
69996  22  30  19  22  23
69997  26  26  26  18   9
69998  28  22   8  28  30
69999   8  12  28   9   6

[70000 rows x 5 columns]