In [2]:
import pandas as pd
import pandera as pa
import numpy as np
from nptyping import NDArray, Shape, Int64

## DataFrame

   * add new column
      *  one column
      *  two or more columns

   * delete column

   * change data type of columns

   * map

   * apply
      *  on one column
      *  more than one column

   * concat
      *  axis
         *   axis = 0 (top to bottom)
         *   axis = 1 (left to right)

   * describe dataframe
     *   df.info() # total index, columns names and data type, total fill cells
     *   df.describe() # mean, std, min # statistical properties | apply only numeric columns
     *   df.head() # first 5 rows
     *   df.tail() # last 5 rows

   * dataframe.sample() # select samples

In [3]:
total : int = 10000
s1 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(80, 100, (total,5))
ss1 : pd.DataFrame = pd.DataFrame(s1,columns=['s1','s2','s3','s4','s5'])

s2 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(70, 79,(total,5))
ss2 : pd.DataFrame = pd.DataFrame(s2,columns=['s1','s2','s3','s4','s5'])

s3 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(60, 69, (total,5))
ss3 : pd.DataFrame = pd.DataFrame(s3,columns=['s1','s2','s3','s4','s5'])

s4 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(50, 59, (total,5))
ss4 : pd.DataFrame = pd.DataFrame(s4,columns=['s1','s2','s3','s4','s5'])

s5 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(40, 49, (total,5))
ss5 : pd.DataFrame = pd.DataFrame(s5,columns=['s1','s2','s3','s4','s5'])

s6 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(33, 39, (total,5))
ss6 : pd.DataFrame = pd.DataFrame(s6,columns=['s1','s2','s3','s4','s5'])

s7 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(0, 32, (total,5))
ss7 : pd.DataFrame = pd.DataFrame(s7,columns=['s1','s2','s3','s4','s5'])


print(s1)
print(s2)
print(s3)
print(s4)
print(s5)


print(len(ss1))
print(len(ss2))
print(len(ss3))
print(len(ss4))
print(len(ss5))
print(len(ss6))
print(len(ss7))

[[82 97 81 99 91]
 [90 92 83 89 85]
 [98 84 96 87 89]
 ...
 [86 90 90 88 83]
 [96 92 83 93 94]
 [92 90 87 81 90]]
[[70 76 71 78 73]
 [75 76 76 73 77]
 [70 75 74 70 72]
 ...
 [75 73 71 77 77]
 [76 73 70 73 75]
 [70 78 75 72 72]]
[[66 66 66 61 63]
 [63 68 65 66 64]
 [63 62 64 67 65]
 ...
 [60 64 64 67 66]
 [64 66 61 67 63]
 [63 67 61 63 64]]
[[56 51 57 54 54]
 [57 53 54 50 53]
 [51 57 57 58 52]
 ...
 [52 56 56 50 56]
 [58 58 57 56 58]
 [56 58 51 58 55]]
[[47 43 42 46 46]
 [40 42 44 40 40]
 [40 47 45 46 45]
 ...
 [46 47 44 44 46]
 [48 48 42 44 48]
 [43 46 43 43 40]]
10000
10000
10000
10000
10000
10000
10000


In [4]:
ss5

s1  s2  s3  s4  s5
0     47  43  42  46  46
1     40  42  44  40  40
2     40  47  45  46  45
3     48  40  46  44  44
4     42  47  47  45  44
...   ..  ..  ..  ..  ..
9995  40  44  42  45  46
9996  40  47  46  47  43
9997  46  47  44  44  46
9998  48  48  42  44  48
9999  43  46  43  43  40

[10000 rows x 5 columns]

In [5]:
df : pd.DataFrame = pd.concat([ss1,ss2,ss3,ss4,ss5,ss6,ss7]).reset_index(drop=True)

display(df.info())
print("================================================================")
display(df.describe())
print("================================================================")
display(df.head())# .head(n=60)
display("================================================================")
display(df.tail())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   s1      70000 non-null  int32
 1   s2      70000 non-null  int32
 2   s3      70000 non-null  int32
 3   s4      70000 non-null  int32
 4   s5      70000 non-null  int32
dtypes: int32(5)
memory usage: 1.3 MB


None

s1            s2            s3            s4            s5
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000
mean      53.767900     53.784329     53.787829     53.804814     53.792714
std       23.365568     23.363820     23.408576     23.413007     23.396672
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%       37.000000     37.000000     37.000000     37.000000     37.000000
50%       54.000000     54.000000     54.000000     54.000000     54.000000
75%       72.000000     72.000000     72.000000     72.000000     72.000000
max       99.000000     99.000000     99.000000     99.000000     99.000000

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

'================================================================'

s1  s2  s3  s4  s5
69995   5  20   2  22  29
69996   2  16  11  27   2
69997  24  24  15  22  19
69998   9  25  13  17  12
69999  30   1   5  11  17

In [6]:
df.to_csv("student.csv", index=False)

In [7]:
df1 : pd.DataFrame = pd.read_csv("./student.csv")
df1.head()

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

## Apply operations on columns

   * Extract one column from DataFrame
      *  dataframe['column']
          *  add new column
          *  get column with space between columns text
      *  dataframe.column
          *  not add new column
          *  not get column with space between columns text
   * Extract two or more columns from DataFrame
      *  dataframe[['column1', 'column2']]
          *  pass list into DataFrame



In [8]:
df.head()

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

In [9]:
df['s5']
# df['s5 physic']

0        91
1        85
2        89
3        90
4        86
         ..
69995    29
69996     2
69997    19
69998    12
69999    17
Name: s5, Length: 70000, dtype: int32

In [10]:
df.s5

0        91
1        85
2        89
3        90
4        86
         ..
69995    29
69996     2
69997    19
69998    12
69999    17
Name: s5, Length: 70000, dtype: int32

In [11]:
df[["s1","s5","s3","s1"]]

s1  s5  s3  s1
0      82  91  81  82
1      90  85  83  90
2      98  89  96  98
3      84  90  97  84
4      88  86  91  88
...    ..  ..  ..  ..
69995   5  29   2   5
69996   2   2  11   2
69997  24  19  15  24
69998   9  12  13   9
69999  30  17   5  30

[70000 rows x 4 columns]

## Add new column

 *   Addition operation on column



In [12]:
df.head()

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

In [17]:
df['Total'] = 500 # add new column
# df['Total'] = 300 # update column values
# df['Total'] = 500 # add new column
# del df['Total']

df



s1  s2  s3  s4  s5  Total
0      82  97  81  99  91    500
1      90  92  83  89  85    500
2      98  84  96  87  89    500
3      84  88  97  97  90    500
4      88  88  91  95  86    500
...    ..  ..  ..  ..  ..    ...
69995   5  20   2  22  29    500
69996   2  16  11  27   2    500
69997  24  24  15  22  19    500
69998   9  25  13  17  12    500
69999  30   1   5  11  17    500

[70000 rows x 6 columns]

In [24]:
# df.Total = 500 # not add new column
# df['Total'] = 500 # add new column
df.Total = 500 # update column values
df['Total'] = 500 # add new column
# del df.Total #  not remove old c

df

AttributeError: 'DataFrame' object has no attribute 'Total'

In [25]:
display(df.head())

s1  s2  s3  s4  s5  Total
0  82  97  81  99  91    500
1  90  92  83  89  85    500
2  98  84  96  87  89    500
3  84  88  97  97  90    500
4  88  88  91  95  86    500

In [27]:
# print(89 + 89 + 86 + 86 + 92)
df['s1'] + df['s2'] + df['s3'] + df['s4'] + df['s5']



0        450
1        439
2        454
3        456
4        448
        ... 
69995     78
69996     58
69997    104
69998     76
69999     64
Length: 70000, dtype: int32

In [28]:
df['obtained'] = df['s1'] + df['s2'] + df['s3'] + df['s4'] + df['s5']
df['percentage'] = df['obtained'] / df['Total'] * 100
df

s1  s2  s3  s4  s5  Total  obtained  percentage
0      82  97  81  99  91    500       450        90.0
1      90  92  83  89  85    500       439        87.8
2      98  84  96  87  89    500       454        90.8
3      84  88  97  97  90    500       456        91.2
4      88  88  91  95  86    500       448        89.6
...    ..  ..  ..  ..  ..    ...       ...         ...
69995   5  20   2  22  29    500        78        15.6
69996   2  16  11  27   2    500        58        11.6
69997  24  24  15  22  19    500       104        20.8
69998   9  25  13  17  12    500        76        15.2
69999  30   1   5  11  17    500        64        12.8

[70000 rows x 8 columns]

## apply custom function on columns(SeriesData)

In [29]:
def grade(per: int)->str:
    if per >= 80:
        return "A+"
    elif per >= 70:
        return "A"
    elif per >= 60:
        return "B"
    elif per >= 50:
        return "C"
    elif per >= 40:
        return "D"
    elif per >= 33:
        return "E"
    else:
        return "F"

grade(82)

'A+'

In [30]:
df.head()

s1  s2  s3  s4  s5  Total  obtained  percentage
0  82  97  81  99  91    500       450        90.0
1  90  92  83  89  85    500       439        87.8
2  98  84  96  87  89    500       454        90.8
3  84  88  97  97  90    500       456        91.2
4  88  88  91  95  86    500       448        89.6

In [31]:
df['percentage'].apply(grade)

0        A+
1        A+
2        A+
3        A+
4        A+
         ..
69995     F
69996     F
69997     F
69998     F
69999     F
Name: percentage, Length: 70000, dtype: object

In [32]:
df['Grade'] = df['percentage'].apply(grade)
df

s1  s2  s3  s4  s5  Total  obtained  percentage Grade
0      82  97  81  99  91    500       450        90.0    A+
1      90  92  83  89  85    500       439        87.8    A+
2      98  84  96  87  89    500       454        90.8    A+
3      84  88  97  97  90    500       456        91.2    A+
4      88  88  91  95  86    500       448        89.6    A+
...    ..  ..  ..  ..  ..    ...       ...         ...   ...
69995   5  20   2  22  29    500        78        15.6     F
69996   2  16  11  27   2    500        58        11.6     F
69997  24  24  15  22  19    500       104        20.8     F
69998   9  25  13  17  12    500        76        15.2     F
69999  30   1   5  11  17    500        64        12.8     F

[70000 rows x 9 columns]


## apply custom function on multiple columns and retunr on column or more than one

   * loc
      *  dataframe[rows,columns]
          *  excact labels value
   * iloc
      *  dataframe[rows,columns]
          *  numerical indexing value
   * at
      *  cell value with exact label
   * iat
      *  cell value with numerical index



In [33]:
df1.head()

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

In [50]:
# df1[0:10] # direct sicling apply on  rows index
# df1.iloc[1:11 , 1:3] # numpy sicling apply on columns and rows index
# df1.loc[1:11,"s1":"s3"] # direct sicling apply on columns and rows labels
# df1.at[4,"s3"]
# df1.iat[4,3]

s2  s3
1   92  83
2   84  96
3   88  97
4   88  91
5   92  90
6   96  86
7   84  93
8   82  99
9   99  98
10  98  83

## Apply custom function on multiple columns and return one column

In [45]:
df1.head()

s1  s2  s3  s4  s5
0  82  97  81  99  91
1  90  92  83  89  85
2  98  84  96  87  89
3  84  88  97  97  90
4  88  88  91  95  86

In [49]:
def fn_obtained(s1: int, s2: int, s3: int, s4: int, s5: int)->int:
    return s1 + s2 + s3 + s4 + s5


df1[["s1", "s2", "s3", "s4", "s5"]].apply(fn_obtained)

TypeError: fn_obtained() missing 4 required positional arguments: 's2', 's3', 's4', and 's5'

In [47]:
def fn_obtained(s1: int, s2: int, s3: int, s4: int, s5: int)->int:
    return s1 + s2 + s3 + s4 + s5


df1['obtained'] = df1[["s1", "s2", "s3", "s4", "s5"]].apply(lambda x:fn_obtained(*x), axis=1)
df1



s1  s2  s3  s4  s5  obtained
0      82  97  81  99  91       450
1      90  92  83  89  85       439
2      98  84  96  87  89       454
3      84  88  97  97  90       456
4      88  88  91  95  86       448
...    ..  ..  ..  ..  ..       ...
69995   5  20   2  22  29        78
69996   2  16  11  27   2        58
69997  24  24  15  22  19       104
69998   9  25  13  17  12        76
69999  30   1   5  11  17        64

[70000 rows x 6 columns]

In [55]:
def fn_obtained(s1: int, s2: int, s3: int, s4: int, s5: int)->tuple[int, int,float, str]:
    total: int = 500
    obtained :int = s1 + s2 + s3 + s4 + s5
    per : float = obtained / total * 100
    grade : str = ""
    if per >= 80:
        grade =  "A+"
    elif per >= 70:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 50:
        grade = "C"
    elif per >= 40:
        grade = "D"
    elif per >= 33:
        grade = "E"
    else:
        grade = "F"
    return total, obtained, per, grade


df1[["Total",'obtained', 'percentage', "Grade"]] = df1[["s1", "s2", "s3", "s4", "s5"]].apply(lambda x:fn_obtained(*x), 
                                                                                             axis=1,
                                                                                             result_type='expand')
df1

s1  s2  s3  s4  s5  obtained  Total  percentage Grade
0      82  97  81  99  91       450    500        90.0    A+
1      90  92  83  89  85       439    500        87.8    A+
2      98  84  96  87  89       454    500        90.8    A+
3      84  88  97  97  90       456    500        91.2    A+
4      88  88  91  95  86       448    500        89.6    A+
...    ..  ..  ..  ..  ..       ...    ...         ...   ...
69995   5  20   2  22  29        78    500        15.6     F
69996   2  16  11  27   2        58    500        11.6     F
69997  24  24  15  22  19       104    500        20.8     F
69998   9  25  13  17  12        76    500        15.2     F
69999  30   1   5  11  17        64    500        12.8     F

[70000 rows x 9 columns]

## Map function for remaks

In [56]:
from typing import Dict


remark : Dict[str,str] = {
    "A+" : "Excellent",
    "A" : "Very Good",
    "B" : "Good",
    "C" : "Fair",
    "D" : "Poor",
    "E" : "Very Poor",
    "F": "Fail"
}

df1['Remark'] = df1.Grade.map(remark)
df1



s1  s2  s3  s4  s5  obtained  Total  percentage Grade     Remark
0      82  97  81  99  91       450    500        90.0    A+  Excellent
1      90  92  83  89  85       439    500        87.8    A+  Excellent
2      98  84  96  87  89       454    500        90.8    A+  Excellent
3      84  88  97  97  90       456    500        91.2    A+  Excellent
4      88  88  91  95  86       448    500        89.6    A+  Excellent
...    ..  ..  ..  ..  ..       ...    ...         ...   ...        ...
69995   5  20   2  22  29        78    500        15.6     F       Fail
69996   2  16  11  27   2        58    500        11.6     F       Fail
69997  24  24  15  22  19       104    500        20.8     F       Fail
69998   9  25  13  17  12        76    500        15.2     F       Fail
69999  30   1   5  11  17        64    500        12.8     F       Fail

[70000 rows x 10 columns]

## Type casting on column names

   * astype
   * apply
      *  datatype name (str, int,list)
      *  function name (cell_value): transformation in function body



In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   s1          70000 non-null  int64  
 1   s2          70000 non-null  int64  
 2   s3          70000 non-null  int64  
 3   s4          70000 non-null  int64  
 4   s5          70000 non-null  int64  
 5   obtained    70000 non-null  int64  
 6   Total       70000 non-null  int64  
 7   percentage  70000 non-null  float64
 8   Grade       70000 non-null  object 
 9   Remark      70000 non-null  object 
dtypes: float64(1), int64(7), object(2)
memory usage: 5.3+ MB


In [58]:
df1['s1'] = df1['s1'].astype(np.int32)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   s1          70000 non-null  int32  
 1   s2          70000 non-null  int64  
 2   s3          70000 non-null  int64  
 3   s4          70000 non-null  int64  
 4   s5          70000 non-null  int64  
 5   obtained    70000 non-null  int64  
 6   Total       70000 non-null  int64  
 7   percentage  70000 non-null  float64
 8   Grade       70000 non-null  object 
 9   Remark      70000 non-null  object 
dtypes: float64(1), int32(1), int64(6), object(2)
memory usage: 5.1+ MB


In [59]:
df1['s2'] = df1['s2'].apply(np.int64)
df1.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   s1          70000 non-null  int32  
 1   s2          70000 non-null  int64  
 2   s3          70000 non-null  int64  
 3   s4          70000 non-null  int64  
 4   s5          70000 non-null  int64  
 5   obtained    70000 non-null  int64  
 6   Total       70000 non-null  int64  
 7   percentage  70000 non-null  float64
 8   Grade       70000 non-null  object 
 9   Remark      70000 non-null  object 
dtypes: float64(1), int32(1), int64(6), object(2)
memory usage: 5.1+ MB
